---
- name: Check mdstat for raid
  shell:
    cmd: 'grep "md" /proc/mdstat'
    executable: bash
  register: __mdraid_avail
  failed_when: __mdraid_avail.rc >= 2
  changed_when: False

- name: Updating zabbix_agent2.conf
  blockinfile:
    dest: /etc/zabbix/zabbix_agent2.conf
    marker: "# {mark} ansible MD SOFT RAID"
    block: |
      UserParameter=md.discover,ls /sys/class/block | awk 'BEGIN{printf "{\"data\":["}; /^md[0-9]+$/ {printf c"{\"{{ '{#' }}MDNAME}\":\""$1"\"}";c=","}; END{print "]}"}'
      UserParameter=md.degraded[*],cat /sys/block/$1/md/degraded
      UserParameter=md.sync_action[*],cat /sys/block/$1/md/sync_action
      UserParameter=md.raid_disks[*],cat /sys/block/$1/md/raid_disks
  when: __mdraid_avail.rc == 0
  notify: Restart and enable zabbix-agent2