---
- name: Ping hosts
  ping:

- name: Check OS
  ansible.builtin.debug:
    msg: "{{ ansible_os_family }}-{{ ansible_distribution }}{{ ansible_distribution_version }}-{{ ansible_distribution_release }}"

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Remove wazuh-agent
  ansible.builtin.apt:
    name: wazuh-agent
    state: absent
  when: ansible_os_family == "Debian"
